---
# - name: "debug vars"
#   ansible.builtin.debug:
#     var: expect[inventory_hostname]

- name: "Debug show command"
  ansible.builtin.debug:
    msg: "{{ item.command }}"
  loop: "{{ expect[inventory_hostname] }}"
  loop_control:
    label: " "
  delegate_to: localhost

- name: "Get show"
  junipernetworks.junos.junos_command:
    commands: "{{ item.command }}"
    display: xml
  register: res_show
  loop: "{{ expect[inventory_hostname] }}"
  loop_control:
    label: " "

- name: "Parse xml"
  community.general.xml:
    xmlstring: "{{ item.stdout[0] }}"
    xpath: "//{{ item.item.element }}"
    content: text
  loop: "{{ res_show.results }}"
  loop_control:
    label: " "
  register: res_xml

- name: "Debug parsed xml"
  ansible.builtin.debug:
    msg:
      - "command: {{ item.item.item.command }}"
      - "element: {{ item.item.item.element }}"
      - "expect: {{ item.item.item.result[inspect_before_or_after] }}"
      - "actual: {{ item.matches[0][item.item.item.element] | trim }}"
  loop: "{{ res_xml.results }}"
  loop_control:
    label: " "

- name: "Assert"
  ansible.builtin.assert:
    that:
      - actual_status == expected_status
    quiet: true
  vars:
    actual_status: "{{ item.matches[0][item.item.item.element] | trim }}"
    expected_status: "{{ item.item.item.result[inspect_before_or_after] }}"
  loop: "{{ res_xml.results }}"
  loop_control:
    label: " "
  when:
    - item.item.item.result[inspect_before_or_after] != None
