---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: get working directory
      ansible.builtin.shell: pwd
      register: result

    - name: debug working directory
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"

    - name: set test string
      ansible.builtin.set_fact:
        directory: "/home/ec2-user/auto_check_config_project"

    - name: debug test string
      ansible.builtin.debug:
        msg: "{{ directory }}"

    - name: assert
      ansible.builtin.assert:
        that: "{{ result.stdout == directory }}"

    - name: ternary
      ansible.builtin.debug:
        msg: "{{ (result.stdout == directory) | ternary('一致している', '一致していない')  }}"