---
version: 3

# build_arg_defaults:
#   ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  ansible_core:
    package_pip: ansible-core==2.14.6
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - junipernetworks.junos
      - community.general
      - arista.eos
  python:
    - ncclient
    - jmespath
    - lxml
    - paramiko
  system:
    - iputils
    - net-tools
    - git

images:
  base_image:
    name: rockylinux:9.1

# additional_build_files:
#     - src: files/ansible.cfg
#       dest: configs

additional_build_steps:
  # prepend_galaxy:
  #   - ADD _build/configs/ansible.cfg ~/.ansible.cfg
  #   - ADD _build/configs/ansible.cfg ~/.ansible.cfg

  append_base:
    - RUN pip3 install --upgrade pip setuptools

  append_final:
    - RUN ln -nfs /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
