---
- name: "Test show"
  hosts: junos
  gather_facts: false
  vars:
    path_to_material: "{{ playbook_dir }}/../material"

  tasks:
    - name: "Include_vars operation"
      ansible.builtin.include_vars:
        file: "{{ path_to_material }}/operation.yaml"
      delegate_to: localhost

    - name: "Include_vars expect"
      ansible.builtin.include_vars:
        file: "{{ path_to_material }}/{{ operation }}/expect.yaml"
        name: expect
      delegate_to: localhost

    - name: "Import inspect"
      ansible.builtin.import_role:
        name: inspect
      vars:
        inspect_before_or_after: before
        inspect_show_target_hosts: "{{ expect.keys() }}"
      when:
        - inventory_hostname in inspect_show_target_hosts

    - name: "Find files"
      ansible.builtin.find:
        paths: "{{ path_to_material }}/{{ operation }}/config"
      register: filenames

    - name: "Import commit"
      ansible.builtin.import_role:
        name: commit
      vars:
        commit_config_target_hosts: "\
          {{ filenames.files | map(attribute='path') | map('basename') }}"
        commit_config_path: "\
          {{ path_to_material }}/{{ operation }}\
          /config/{{ inventory_hostname }}"
      when:
        - inventory_hostname in commit_config_target_hosts

    - name: "Import inspect"
      ansible.builtin.import_role:
        name: inspect
      vars:
        inspect_before_or_after: after
        inspect_show_target_hosts: "{{ expect.keys() }}"
      when:
        - inventory_hostname in inspect_show_target_hosts
