---
- name: "Connectivity check"
  hosts: junos
  gather_facts: false
  tasks:
    - name: "Get ge-0/0/1 terse"
      junipernetworks.junos.junos_command:
        commands: "show interface ge-0/0/1 terse"
