---
- name: "Shutdown ge-0/0/1"
  hosts: junos
  gather_facts: false

  tasks:
    - name: "Get status ge-0/0/1"
      junipernetworks.junos.junos_command:
        commands: "show interfaces ge-0/0/1 terse"
      register: res_show

    - name: "Debug res_show"
      ansible.builtin.debug:
        msg: "{{ res_show.stdout_lines[0][1] }}"

    - name: "Conf ge-0/0/1"
      junipernetworks.junos.junos_interfaces:
        config:
          - name: ge-0/0/1
            enabled: false

    - name: "Pause 10 seconds"
      ansible.builtin.pause:
        seconds: 10

    - name: "Get status ge-0/0/1"
      junipernetworks.junos.junos_command:
        commands: "show interfaces ge-0/0/1 terse"
      register: res_show

    - name: "Debug res_show"
      ansible.builtin.debug:
        msg: "{{ res_show.stdout_lines[0][1] }}"
