---
- name: "Test show"
  hosts: all
  gather_facts: false

  tasks:
    - name: "Debug"
      ansible.builtin.debug:
        var: inventory_hostname

    - name: "Test show"
      junipernetworks.junos.junos_command:
        commands: "show configuration"
      register: result

    - name: "Debug"
      ansible.builtin.debug:
        var: result.stdout_lines
