---
name: commit_and_inspect
run-name: ${{ github.actor }} config change
on:
  push:
    paths:
      - 'project/material/*'

jobs:
  # check_my_ip:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: check my ip
  #       run: curl http://inet-ip.info/

  # approval:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: test
  #   steps:
  #     - run: echo "waiting approval"

  config_CICD:
    # 権限の範囲は要検討
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/apc-nw-auto-cft/auto_check_config_project/ee:1.3
      # credentials:
      #   username: ${{ github.actor }}
      #   password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    env:
      dev_or_prod: ${{ endswith(github.ref, 'develop') && 'develop' || endsWith(github.ref, 'main') && 'production' }}
      commit_msg: ${{github.event.head_commit.message}}
    steps:
      # - uses: actions/checkout@v2
      # - name: Login GitHub Packages
      #   uses: docker/login-action@v1.13.0
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: git operation
        run: echo ${commit_msg}
        if: github.ref == 'refs/heads/develop'

      - name: check my ip
        run: curl http://inet-ip.info/

      - name: checkout code
        uses: actions/checkout@v3

      - name: connectivity_check
        uses: corrupt952/retry-command@v1.0.7
        with:
          command: "\
            ansible-playbook -i project/inventory/${dev_or_prod}/inventory.yaml \
            project/playbook/connectivity_check.yaml"
          max_attempts: 5
          retry_interval: 5

      - name: commit inspect
        run: "\
          ansible-playbook -i project/inventory/${dev_or_prod}/inventory.yaml \
          project/playbook/commit_and_inspect.yaml"

      - name: git Pre-setting
        run: |
          git config --global --add safe.directory /__w/auto_check_config_project/auto_check_config_project
          pwd
          git config --global user.name  "employee"
          git config --global user.email "employee@example.com"
          git status
        if: github.ref == 'refs/heads/develop'

      - name: compare backup
        run: "\
          ansible-playbook -i project/inventory/develop/inventory.yaml \
          project/playbook/compare_and_backup.yaml"
        if: github.ref == 'refs/heads/develop'

      - name: git operation
        run: |
          git status
          pwd
          git add project/backup/.
          git status
        if: github.ref == 'refs/heads/develop'

      - name: git operation
        run: echo ${commit_msg}
        if: github.ref == 'refs/heads/develop'

      - name: git operation
        run: |
          git commit -m ${commit_msg}
        if: github.ref == 'refs/heads/develop'

      - name: git push
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }} #Repository secretsの情報で認証してほしい
        run: |
          git push
        if: github.ref == 'refs/heads/develop'

  create_pull_request:
    runs-on: ubuntu-latest
    needs: config_CICD #1個目のjobsが終わったら実行(無いと並列処理になってしまう)
    if: github.ref == 'refs/heads/develop' #ブランチがdevelopだったら実行
    env:
      GH_TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }} #Repository secretsの情報で認証してほしい
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Create Release Pull Request
        run: |
          gh pr create \
            --base main \
            --head develop \
            --title ${{github.event.head_commit.message}} \
            --body "https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
